name: dart_mail
description: A pure Dart email stack featuring SMTP and IMAP servers, DNS MX resolution, and email relay support.
version: 1.0.0
repository: https://github.com/gmpassos/dart_mail

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  collection: ^1.19.1
  diacritic: ^0.1.6
  dns_client:
    git: https://github.com/gmpassos/dns_client.git
  logging: ^1.3.0
  path: ^1.9.1
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
  mailer: ^6.6.0

#dependency_overrides:
#  dns_client:
#    path: ../dns_client
